In [17]:
import pandas as pd
import numpy as np
from datetime import datetime,timedelta

from sklearn.metrics import mean_squared_error
from scipy.optimize import curve_fit
from scipy.optimize import fsolve
import matplotlib.pyplot as plt
%matplotlib inline

In [18]:
url = "https://raw.githubusercontent.com/pcm-dpc/COVID-19/master/dati-andamento-nazionale/dpc-covid19-ita-andamento-nazionale.csv"
df = pd.read_csv(url)
df.head()

,data,stato,ricoverati_con_sintomi,terapia_intensiva,totale_ospedalizzati,isolamento_domiciliare,totale_positivi,variazione_totale_positivi,nuovi_positivi,dimessi_guariti,deceduti,totale_casi,tamponi,note_it,note_en
0,2020-02-24T18:00:00,ITA,101,26,127,94,221,0,221,1,7,229,4324,NaN,NaN
1,2020-02-25T18:00:00,ITA,114,35,150,162,311,90,93,1,10,322,8623,NaN,NaN
2,2020-02-26T18:00:00,ITA,128,36,164,221,385,74,78,3,12,400,9587,NaN,NaN
3,2020-02-27T18:00:00,ITA,248,56,304,284,588,203,250,45,17,650,12014,NaN,NaN
4,2020-02-28T18:00:00,ITA,345,64,409,412,821,233,238,46,21,888,15695,NaN,NaN

In [19]:
df = df.loc[:,['data','totale_casi']]
FMT = '%Y-%m-%dT%H:%M:%S'
date = df['data']

#df['data'] = date.map(lambda x : (datetime.strptime(x, FMT) - datetime.strptime("2020-01-01 00:00:00", FMT)).days)
size=df.shape[0]
df['data']=[i for i in range(54,(54+size))]
df.head()

   data  totale_casi
0    54          229
1    55          322
2    56          400
3    57          650
4    58          888

In [20]:
'''
x = list(df.iloc[:,0])
y = list(df.iloc[:,1])
'''
x=df['data'].tolist()
y=df['totale_casi'].tolist()

fit = curve_fit(logistic_model,x,y,p0=[2,100,20000])
fit

(array([5.57731007e+00, 8.25929979e+01, 1.34639444e+05]),
 array([[4.75775204e-03, 8.62482889e-03, 8.25398882e+01],
        [8.62482889e-03, 2.13363493e-02, 1.96366282e+02],
        [8.25398882e+01, 1.96366282e+02, 1.91688650e+06]]))